### ISSUE TITLE
Illegal access to actor context in QuorumLossAbdicator abdicate receive

### ISSUE THREAD

**Issue by fdimuccio** [shikhar/eskka#14]
Hi, first of all thank you for this project. While studying it I encountered this piece of code in QuorumLossAbdicator.scala:

``` scala
def abdicate: Actor.Receive = {
    case Abdicate =>
      killSeq.foreach(context.stop)
      SubmitClusterStateUpdate(clusterService, "eskka-quorum-loss-abdicator", Priority.URGENT, runOnlyOnMaster = false, abdicationClusterState) onComplete {
        case Success(_) =>
          log.debug("cleared cluster state, now invoking restart hook")
          restartHook()
        case Failure(e) =>
          log.error(e, "failed to clear cluster state, will retry in {}", CheckInterval)
          context.system.scheduler.scheduleOnce(CheckInterval, self, Abdicate)
      }
  }
```

In the failure handler you are accessing the actor context within the onComplete callback that, If i'm not wrong, could be run in a separate thread than the actor one. One solution could be to pipe the future back to the actor and do the handling there. Feel free to correct me if I missed some piece.

**Comment by shikhar** [comment]
@fdimuccio Good catch! Thanks for the bug report :) That access seems unsafe.
